name = "DecisionRules"
uuid = "47937410-f832-486f-8300-12c95b225dfc"
authors = ["Andrew <arosemberg3@gatech.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
